language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

install:
  - if [[ $TRAVIS_PHP_VERSION = hhvm* ]]; then echo hhvm.php7.all=1 >> /etc/hhvm/php.ini; fi
  - composer install -o

script:
  - composer test
